from enum import StrEnum


class EnvironmentErrorCode(StrEnum):
    SSH_CONNECT_FAILED = "SSH_CONNECT_FAILED"
    UNSUPPORTED_OS = "UNSUPPORTED_OS"
    NO_NVIDIA_GPU = "NO_NVIDIA_GPU"
    DRIVER_NOT_READY = "DRIVER_NOT_READY"
    DOCKER_NOT_INSTALLED = "DOCKER_NOT_INSTALLED"
    NVIDIA_RUNTIME_MISSING = "NVIDIA_RUNTIME_MISSING"
    RUNTIME_VERIFY_FAILED = "RUNTIME_VERIFY_FAILED"
    COMMAND_TIMEOUT = "COMMAND_TIMEOUT"


ENVIRONMENT_ERROR_CODES = {code.value for code in EnvironmentErrorCode}
